//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_item
    {
        public int lesson_id { get; set; }
        public int purchase_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> items_price { get; set; }
    }
}
